# Generated by Django 5.0.6 on 2026-06-24 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('in_progress', 'В работе'), ('completed', 'Завершён'), ('cancelled', 'Отменён клиентом')], db_index=True, default='pending', max_length=15, verbose_name='статус')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Замороженная цена на момент создания заказа', max_digits=10, verbose_name='цена при бронировании')),
                ('scheduled_time', models.DateTimeField(verbose_name='запланированное время')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
                ('client_comment', models.TextField(blank=True, verbose_name='комментарий клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(blank=True, verbose_name='текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
