# Generated by Django 5.0.6 on 2026-06-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.PROTECT, related_name='master_orders', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service', verbose_name='услуга'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='review',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='заказ'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['master', 'status'], name='orders_orde_master__c73f26_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_time'], name='orders_orde_schedul_c7c611_idx'),
        ),
    ]
