# Generated by Django 5.0.6 on 2026-06-27 10:56

import apps.services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, help_text='🎂 🎉 💼 👰', max_length=10, verbose_name='эмодзи')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тип мероприятия',
                'verbose_name_plural': 'типы мероприятий',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.services.models.service_gallery_upload_path, verbose_name='фотография')),
                ('is_main', models.BooleanField(default=False, help_text='Только одно фото может быть главным', verbose_name='главное фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'фото услуги',
                'verbose_name_plural': 'галерея услуги',
                'ordering': ['-is_main', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='иконка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='services.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена от')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_hour', 'За час'), ('per_day', 'За сутки'), ('per_event', 'За мероприятие'), ('per_item', 'За штуку')], default='per_event', max_length=10, verbose_name='тип цены')),
                ('min_duration', models.PositiveSmallIntegerField(blank=True, help_text='В часах (per_hour) или сутках (per_day)', null=True, verbose_name='минимальная длительность')),
                ('cover_image', models.ImageField(blank=True, help_text='Главное фото для быстрой загрузки. Галерея — через ServiceImage.', null=True, upload_to=apps.services.models.service_cover_upload_path, verbose_name='обложка')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube, Vimeo или другой видеохостинг', verbose_name='видео-портфолио')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category', verbose_name='категория')),
                ('event_types', models.ManyToManyField(blank=True, related_name='services', to='services.eventtype', verbose_name='типы мероприятий')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
