# Generated by Django 5.0.6 on 2026-06-24 06:19

import apps.services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='иконка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='services.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('hourly', 'За час')], default='fixed', max_length=10, verbose_name='тип цены')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.services.models.service_cover_upload_path, verbose_name='обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
