# Generated by Django 5.0.6 on 2026-06-27 10:56

import apps.users.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует.'}, max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Формат: '+77001234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='номер телефона')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('master', 'Исполнитель'), ('admin', 'Администратор')], db_index=True, default='client', max_length=10, verbose_name='роль')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Расскажите о себе и своих услугах', verbose_name='описание')),
                ('city', models.CharField(choices=[('astana', 'Астана'), ('almaty', 'Алматы'), ('shymkent', 'Шымкент'), ('atyrau', 'Атырау'), ('aktau', 'Актау'), ('aktobe', 'Актобе'), ('karaganda', 'Караганда'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Усть-Каменогорск'), ('semey', 'Семей'), ('uralsk', 'Уральск'), ('kostanay', 'Костанай'), ('kyzylorda', 'Кызылорда'), ('petropavlovsk', 'Петропавловск'), ('kokshetau', 'Кокшетау'), ('turkestan', 'Туркестан')], db_index=True, default='atyrau', max_length=20, verbose_name='город')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='рейтинг')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='количество отзывов')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Подтверждён администратором платформы', verbose_name='верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль исполнителя',
                'verbose_name_plural': 'профили исполнителей',
            },
        ),
    ]
