# Generated by Django 5.0.6 on 2026-06-24 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='null = системное сообщение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['order', 'created_at'], name='msg_order_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['order', 'created_at', 'is_system'], name='msg_order_time_system_idx'),
        ),
    ]
