# Generated by Django 5.0.6 on 2026-06-28 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='False = непрочитано получателем. Системные сообщения помечаются прочитанными при создании.', verbose_name='прочитано'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['order', 'is_read', 'sender'], name='msg_order_unread_idx'),
        ),
    ]
